cookpad/cp8

- README.md
> Revert merge [Delivers #586f50b384a655b5c009c4ca]

- lib/events/pull_request.rb
Starting out on the conservative side by shortening it by a week 😅 
CC @firewalker06
> Shorten length of "stale issues"

- README.md
Trello: https://trello.com/c/c55LPQEz
> test weird card moving bug [Delivers #c55LPQEz]

- README.md
> Revert "test weird card moving bug"

- lib/user_mappings.yml
> Add mapping for @tomoya55 to cp-8

- lib/user_mappings.yml
Correct mapping for @dannyd4315
> Update user mappings for @dannyd4315

- lib/issue_delegator.rb
- test/fixtures/move_to_label.json
- test/processor_test.rb
Mention the original submitter when moving an issue for reference
> Mention original submitter when moving issue

- README.md
This should be linked to from web-chapter onboarding
> Add user mapping instructions

- lib/user_mappings.yml
Adding @andrassy @mattjw @radeklat slack ids
> Add search team members to user mappings

- lib/user_mappings.yml
Add myself for usermapping for better CP8 integration
> Add user `lazlyhu` for mapping

- lib/buddy_mappings.yml
- lib/buddy_mention.rb
- lib/buddy_resolver.rb
- lib/processor.rb
- lib/user.rb
- test/buddy_resolver_test.rb
- test/processor_test.rb
Bit of automation for https://github.com/cookpad/web-chapter/issues/410
> Support buddy system try-out

- lib/user_mappings.yml
https://github.com/cookpad/web-chapter/issues/434
> Map my GitHub user id to my slack id

- lib/buddy_mappings.yml
Reference: https://github.com/cookpad/web-chapter/issues/410#issuecomment-679439673
> add buddy mappings for try-out

- lib/buddy_resolver.rb
- lib/user.rb
- test/buddy_resolver_test.rb
Fixes issue with case sensitivity in user names.
Closes https://github.com/cookpad/cp8/pull/114
> handle case sensitivity

- lib/buddy_mappings.yml
I'm back! 👋 
Timezone-wise, it makes more sense for me to pair with Arty, as we're sharing more hours in common.
> Add myself and Jesse back to buddies

- lib/user_mappings.yml
Add my slack id to the user mappings
> add myself to the user mappings

- lib/user_mappings.yml
Fix typo in my own name as pointed out in https://github.com/cookpad/cp8/pull/122#issuecomment-753901106
> Fix typo in `tony-ronywan` 

- lib/buddy_mappings.yml
- lib/user_mappings.yml
[👋🏻 Arty 😢](https://github.com/cookpad/web-chapter/pull/671)
> Remove mappings for artygus

- lib/user_mappings.yml
Adding mapping for mromeos
Thank you
> add search team member mromeos to user_mappings

- lib/buddy_mappings.yml
> parting with my buddy 😥

- lib/user_mappings.yml
This PR is related to my onboarding issue:  https://github.com/cookpad/search-engineering/issues/3332
Could you please  add me to cp8's user_mappings? Thanks!
> Adding mapping for panagiotis-bailis-cookpad
