cookpad/cp8

Gemfile, Gemfile.lock, Rakefile, lib/label.rb, test/payload_test.rb
Strangely GitHub will sometimes show the "CP-8 added label" when trying to add a label that has already been added. This makes sure labels are only added/removed if they haven't been already.
=> avoid unnecessary removed/added messages

lib/event/pull_request.rb, test/payload_test.rb
Scans for old PRs issues whenever a PR changes (in lieu of a proper cron job for now).
Will eventually automatically close issues.
=> Automatically add comment to stale issues/PRs

README.md, lib/configuration.rb, lib/issue.rb, lib/payload.rb, lib/processor.rb, lib/project_manager.rb, test/processor_test.rb
This PR contains the implementation of a feature requested here: https://github.com/cookpad/cp8/issues/40
When enabled, cp8 will move newly created issues to a predefined column in one of the repository projects.
Project column has to be defined in the payload like so:
`/payload?config[project_column_id]=49 # Move newly created issues to this project column`
Without the defined `project_column_id` cp8 this feature will be disabled.
=> Add new issues to project

lib/user.rb
After bumping Puma to 3.12.0, it seems we need to explicitly require "yaml".
```
2018-08-21T11:04:06.543270+00:00 app[web.1]: Puma starting in single mode...
2018-08-21T11:04:06.543291+00:00 app[web.1]: * Version 3.12.0 (ruby 2.4.2-p198), codename: Llamas in Pajamas
2018-08-21T11:04:06.543292+00:00 app[web.1]: * Min threads: 5, max threads: 5
2018-08-21T11:04:06.543294+00:00 app[web.1]: * Environment: production
2018-08-21T11:04:07.321628+00:00 app[web.1]: ! Unable to load application: NameError: uninitialized constant User::YAML
2018-08-21T11:04:07.321840+00:00 app[web.1]: bundler: failed to load command: puma (/app/vendor/bundle/ruby/2.4.0/bin/puma)
2018-08-21T11:04:07.321965+00:00 app[web.1]: NameError: uninitialized constant User::YAML
2018-08-21T11:04:07.321967+00:00 app[web.1]: …
```
=> require yaml

README.md, lib/configuration.rb, lib/payload.rb, lib/processor.rb, lib/project_manager.rb, test/processor_test.rb
As our [past selves already knew](https://github.com/cookpad/cp8/issues/40#issuecomment-395243072), but our current selves foolishly forgot, the GitHub automation feature actually only works if you _manually_ add an issue to a project first, and what this feature does is automatically add _any_ new issue to a project board column.
cc @pauchan
=> Bring back project manager feature :D

lib/issue_delegator.rb, test/processor_test.rb
`move-to` feature will require CP8 to have permissions to the target repo, but when it doesn't it just fails silently.
This makes CP8 post back that something went wrong 😅
=> show a more helpful error message when things go wrong

README.md
The CLI should be linked in the README to make it easier for developers to see how the tools can work together to further automize workflows.
It might also help our new Cookpad employees (like me!) to find the right gem to install after updating the Ruby version and wondering why `cp8 command` does no longer work ;-)
=> Link to cp8_cli in README

lib/user.rb, test/user_test.rb
because usernames are case insensitive on GitHub so
we should support his.
As pointed out by @balvig & @davidstosik, thanks 🙏
=> Make GitHub -> Slack user mapping case insensitive

lib/notifications/review_request_notification.rb, test/processor_test.rb
Closes #72.
Alternative to #72, this shows the repo name as one of the "attachments", and only for request message (ie "approved/changes requested" don't show them, as it seems unnecessary for that stage):
cc @sikachu
=> Show repo for review requests

lib/notifications/review_complete_notification.rb, test/processor_test.rb
In our handbook, when reviewing we encourage [picking _either approve or request changes_](https://github.com/cookpad/web-chapter/blob/master/handbook/practices/code-review.md#reviewing):
> Choose either "request changes" or "approve" so the author knows how to proceed.
I _think_ the reasoning is fairly solid: a PR submitter needs to understand where they're at after a review.
The GitHub UI at the time of writing defines it as such:
- **Approve:** Submit feedback and approve merging these changes.
- **Request changes:** Submit feedback that must be addressed before merging.
- **Comment:** Submit general feedback without explicit approval.
So while first two are really clear, what should you do when given "general feedback"? 😅 
- How strongly does the reviewer feel about the comment?
- …
=> soften tone of changes_requested notification

lib/issue_title.rb, test/issue_title_test.rb
https://api.slack.com/docs/message-formatting
See e.g. https://ckpd.slack.com/archives/C8GQ6ND3P/p1559201762001000
=> According to the Slack docs we need to escape <>& chars

lib/user_mappings.yml
I noticed in the [#review](https://ckpd.slack.com/archives/C8GQ6ND3P/p1588181595126500) channel that alinagrishchuk wasn't mapped to the slack account
=> Add alinagrishchuk to user mappings

lib/buddy_mention.rb
In https://github.com/cookpad/cp8/commit/d2c580cc7629d3e8521ddd54de585922d5a61927 buddy system issue link was set to flaky spec [issue](https://github.com/cookpad/web-chapter/issues/411), looks like it was not intended change. This PR sets it back 😉
=> Proper buddy sytem issue link

lib/buddy_mappings.yml
As I will be off for at least a month, I thought it would work to have @sikachu replace me as @firewalker06's _buddy™_.
@artygus should be back with us in a couple weeks, so that's an alternative to consider.
=> Give a buddy to Didik while I'll be away

lib/notifications/review_complete_notification.rb, lib/payload.rb, lib/review.rb, test/processor_test.rb
The behavior that suppresses notification for reviews which neither approve nor request changes was added hand in hand with the guideline in https://github.com/cookpad/web-chapter/blob/master/handbook/sections/code-review.md#reviewing:
> Choose either "request changes" or "approve" so the author knows how to proceed.
Being clear about how strongly we feel about comments in a review is still crucial, but somehow I still find situations where the choice between approve/request changes is difficult.
For example, [if I need to ask more questions first](https://github.com/cookpad/global-web/pull/20938#pullrequestreview-495267545), it's not an approval, but it's not really "REQUEST CHANGES" either. 🤔 
For those cases, I believe it will tighten the review loop if a submitter is notified early on …
=> send notifications for reviews that aren't explicit approval

lib/payload.rb, lib/processor.rb, test/fixtures/submitter_review.json, test/processor_test.rb
Ref: https://ckpd.slack.com/archives/C06B9GD9D/p1601039123029000
GitHub treats any inline comments as "reviews", even if from the PR submitter themselves.
This PR disables those notifications for now. 
We can rely on a ♻️ comment, to notify reviewers once done making changes/answering questions.
=> don't send notifications for submitter comments

lib/issue.rb, lib/payload.rb, lib/user.rb
GitHub API includes a `type` attribute with their users nowadays, so we can rely on that instead of keeping our own list of bots.
=> tiny refactoring enabled by #119

lib/user_mappings.yml
Setting up github to slack user mapping as per: https://github.com/cookpad/cp8/blob/master/README.md#user-mapping
=> Add user mapping for tony-rowan

lib/buddy_mappings.yml
Aqeel is on paternity leave, and Haroon is currently buddy-less, so let's buddy up.
=> Buddy up with Haroon

lib/buddy_mappings.yml
This PR updates the buddy mappings to change Sam J to Tony. 
Sam has left us and @tony-rowan was not on the buddy mappings
=> Update buddy mappings

lib/user_mappings.yml
Adding my mapping for slack. Ben Howes no longer works at Cookpad, have removed that mapping.
Also adds other missing search team members
=> Add search team members to slack mapping, remove Ben Howes
